---
abstract: 'Run CGIs in Catalyst'
author:
  - 'Matt S. Trout <mst@shadowcat.co.uk>'
build_requires:
  CGI: 0
  Catalyst::Plugin::Static::Simple: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-WrapCGI
no_index:
  directory:
    - inc
    - t
provides:
  Catalyst::Controller::CGIBin:
    file: lib/Catalyst/Controller/CGIBin.pm
    version: 0.017
  Catalyst::Controller::WrapCGI:
    file: lib/Catalyst/Controller/WrapCGI.pm
    version: 0.017
  CatalystX::GlobalContext:
    file: lib/CatalystX/GlobalContext.pm
    version: 0.017
requires:
  Catalyst: 5.80002
  File::Find::Rule: 0
  File::Slurp: 0
  HTTP::Request::AsCGI: 0.8
  LWP: 0
  List::MoreUtils: 0
  Moose: 0
  Task::Weaken: 0
  URI: 1.37
  namespace::clean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/trunk/Catalyst-Controller-WrapCGI/
version: 0.017
