---
abstract: 'Run CGIs in Catalyst'
author:
  - 'Matt S. Trout C<< <mst at shadowcat.co.uk> >>'
  - 'Matt S. Trout <mst@shadowcat.co.uk>'
build_requires:
  CGI: 0
  Catalyst::Plugin::Static::Simple: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-WrapCGI
no_index:
  directory:
    - inc
    - t
provides:
  Catalyst::Controller::CGIBin:
    file: lib/Catalyst/Controller/CGIBin.pm
    version: 0.030
  Catalyst::Controller::WrapCGI:
    file: lib/Catalyst/Controller/WrapCGI.pm
    version: 0.030
  CatalystX::GlobalContext:
    file: lib/CatalystX/GlobalContext.pm
    version: 0.030
requires:
  CGI::Compile: 0.07
  Catalyst: 5.80015
  File::Find::Rule: 0
  File::pushd: 0
  HTTP::Request::AsCGI: 1.2
  LWP: 0
  List::MoreUtils: 0
  Moose: 0
  Task::Weaken: 0
  URI: 1.37
  namespace::clean: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Catalyst-Controller-WrapCGI.git
version: 0.030
