---
abstract: 'Run CGIs in Catalyst'
author:
  - 'Matt S. Trout <mst@shadowcat.co.uk>'
build_requires:
  Catalyst::Plugin::Static::Simple: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Controller-WrapCGI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7007
  File::Find::Rule: 0
  File::Slurp: 0
  HTTP::Request::AsCGI: 0.7
  List::MoreUtils: 0
  Moose: 0
  Task::Weaken: 0
  URI: 0
  namespace::clean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.0031
